---
- name: Git install
  apt: pkg=git state=installed
  register: gitinstalled

- name: Add .gitconfig
  when: gitinstalled|success and overwrite_gitconfig == "yes"
  copy: src=git.gitconfig dest=/home/{{ ansible_env.SUDO_USER }}/.gitconfig

- name: Add .gitignore
  when: gitinstalled|success and overwrite_gitignore == "yes"
  copy: src=git.gitignore dest=/home/{{ ansible_env.SUDO_USER }}/.gitignore
