---
#- name: Apt cache update
#  apt: update_cache=true

- name: Install tools
  apt: pkg={{ item }} state=installed
  with_items:
          - tmux # terminal multiplexer
          - htop
          - sysv-rc-conf # service manager
          - jq # json parser

- name: Git install
  apt: pkg=git state=installed
  register: gitinstalled

- name: Add .gitconfig
  when: gitinstalled|success
  copy: src=git.gitconfig dest=/home/{{ whoami }}/.gitconfig

- name: Add .gitignore
  when: gitinstalled|success
  copy: src=git.gitignore dest=/home/{{ whoami }}/.gitignore
