---
- name: common tools
  hosts: local
  sudo: yes
  #remote_user: 
  
  vars:
    - os_family: "Debian"
  
  pre_tasks:
   - name: update apt     
     when: ansible_os_family == os_family
     apt: update_cache=true
        
  roles:
   - debian-common-tools
